### ISSUE TITLE
`string.maketrans` has been deprecated. Update to `bytes.maketrans`

### ISSUE THREAD

**Issue by adam-grant-hendry** [sphinx-contrib/email#3]
As the title suggests, your code fails at `string.maketrans` as this has been deprecated. Please update to use `str.maketrans`.

**Comment by adam-grant-hendry** [comment]
Also remove the line `text = text.decode("utf-8").encode("utf-8")`. `text` is already a string, so no need to decode. Also, you use it like a string object (not a byte object), so you do not want to encode it. Removing this and changing `string.maketrans` to `str.maketrans` fixes your code in Python 3.

**Comment by lcnittl** [comment]
Should be resolved with merge of #2.
